language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-29
script:
- sh gradlew mapwize-ui:javadoc || travis_terminate 1;
- mv mapwize-ui/build/outputs/javadoc docs
- zip -r javadoc.zip docs || travis_terminate 1;
deploy:
- provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "./javadoc.zip"
  skip_cleanup: true
  on:
    tags: true
